### ISSUE TITLE
Import Link

### ISSUE THREAD

**Issue by Zen-Da** [tkloht/react-video-cover#186]
it would be nice to have the import link in the tutorial ... that's a very basic thing to show in as dependencies providers ... great work though

**Comment by tkloht** [comment]
I‘m not sure what you mean by „import link“, just the name of the package on npm?

**Comment by MazenCg** [comment]
thank you for your response. I think I got it figured out ... another small issue is that the video is not playing, I can see it in the browser but it's frozen. any idea how can I get around that?

**Comment by tkloht** [comment]
Is this on some project of yours or on the examples? for example if you go here: http://tkloht.github.io/react-video-cover/background the video should start playing already.

If you have problems using this component in your own project, would it be possible to show me the code? then i'll see what i can do.

**Comment by MazenCg** [comment]
I'm working on a project for my client,

here is an example of what I meant by the import link :
import React from 'react';
import { Link } from "react-scroll";

When using any other dependency, the will have all the needed details in the description.  

there are many beginners just like me will be trying to use your dependency, so maybe expanding on the description a bit would help a lot.

Also for the example page, it would be nice if you could show the code used on the page without the necessity to download a clone from Github ... a link to Codepen would be lovely.

I couldn't eventually use your dependency, most likely due to my poor knowledge, but I managed using a few other dependencies with no problems probably due to their brief description.

Thank you very much for sharing your knowledge any way ^_^

**Comment by MilesLitteral** [comment]
"I also encourage you to have a look at the code, it should be relatively easy to understand."

I'm going to be frank in saying this, it's very hard for one programmer to understand the code of another; I've been reading through the examples and I'm very much at a loss for how to import the VideoCover component and instead just made a <video> html5 object with a css style; It's a cool idea to make it a component but idk.

**Comment by tkloht** [comment]
you don't need this component unless you want to use object-fit need to support IE11, that is the whole point of it. https://caniuse.com/#search=object-fit

this is how you import the component: `import VideoCover from 'react-video-cover';`
taken from this example: https://github.com/tkloht/react-video-cover/blob/master/examples/src/pages/minimal.js

**Comment by MilesLitteral** [comment]
Thanks for clarifying

**Comment by tkloht** [comment]
updated the readme a bit to clarify how to import the component
