### ISSUE TITLE
HLS Streaming Support

### ISSUE THREAD

**Issue by JanOwiesniak** [tkloht/react-video-cover#196]
I tried to play HLS videos e.g. https://player.vimeo.com/external/334901421.m3u8?s=546ff958239147c94e3c966f781f938adbebcffd but this does not seem to work.

Is there any undocumented option to pass HLS urls to the component?

If not, is this something that could be implemented without a lot of hassle?

**Comment by tkloht** [comment]
i don't know much about hls, but might just not work because your browser doesn't support it https://caniuse.com/#feat=http-live-streaming

i can try if i get a test to work in safari later, that should work at least - i'm just rendering a video tag after all. 
If you want to try for yourself, maybe look over here https://github.com/tkloht/react-video-cover/blob/master/lib/index.js#L33. Everything that you pass as videoOptions prop will be passed to the video tag.

**Comment by tkloht** [comment]
i realize this answer is coming terribly late, sorry for that. HLS streaming works just fine, see this  [example](http://tkloht.github.io/react-video-cover/hls/) ([source](https://github.com/tkloht/react-video-cover/blob/master/examples/src/pages/hls.js#L24))

keep in mind that this will only work in safari, which defeats the purpose of this component to some extent because it is mainly meant to support the css property object-fit on videos if you _need_ to support IE11. If you are targeting safari exclusively, you are most likely better off just using object-fit directly.
